package com.example.hectorvera.batteryconectionbroadcast.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.hectorvera.batteryconectionbroadcast.db.History;
import com.example.hectorvera.batteryconectionbroadcast.db.difference;

import com.example.hectorvera.batteryconectionbroadcast.db.HistoryDao;
import com.example.hectorvera.batteryconectionbroadcast.db.differenceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig historyDaoConfig;
    private final DaoConfig differenceDaoConfig;

    private final HistoryDao historyDao;
    private final differenceDao differenceDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        historyDaoConfig = daoConfigMap.get(HistoryDao.class).clone();
        historyDaoConfig.initIdentityScope(type);

        differenceDaoConfig = daoConfigMap.get(differenceDao.class).clone();
        differenceDaoConfig.initIdentityScope(type);

        historyDao = new HistoryDao(historyDaoConfig, this);
        differenceDao = new differenceDao(differenceDaoConfig, this);

        registerDao(History.class, historyDao);
        registerDao(difference.class, differenceDao);
    }
    
    public void clear() {
        historyDaoConfig.getIdentityScope().clear();
        differenceDaoConfig.getIdentityScope().clear();
    }

    public HistoryDao getHistoryDao() {
        return historyDao;
    }

    public differenceDao getDifferenceDao() {
        return differenceDao;
    }

}
