package com.example.hectorvera.batteryconectionbroadcast.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DIFFERENCE".
 */
public class difference {

    private Long id;
    private Long Interval;

    public difference() {
    }

    public difference(Long id) {
        this.id = id;
    }

    public difference(Long id, Long Interval) {
        this.id = id;
        this.Interval = Interval;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getInterval() {
        return Interval;
    }

    public void setInterval(Long Interval) {
        this.Interval = Interval;
    }

}
