package com.example.hectorvera.batteryconectionbroadcast.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "HISTORY".
 */
public class History {

    private Long id;
    private String Status;
    private Long Date;

    public History() {
    }

    public History(Long id) {
        this.id = id;
    }

    public History(Long id, String Status, Long Date) {
        this.id = id;
        this.Status = Status;
        this.Date = Date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getStatus() {
        return Status;
    }

    public void setStatus(String Status) {
        this.Status = Status;
    }

    public Long getDate() {
        return Date;
    }

    public void setDate(Long Date) {
        this.Date = Date;
    }

}
